# Generated by Django 6.0.3 on 2026-03-06 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('rede_cidr', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloco de IP',
                'verbose_name_plural': 'Blocos de IP',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('import', 'Importação')], max_length=20)),
                ('entidade', models.CharField(max_length=100)),
                ('entidade_id', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_novo', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_processados', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('executado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_accounts', to='core.client')),
            ],
            options={
                'verbose_name': 'Conta PPPoE',
                'verbose_name_plural': 'Contas PPPoE',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PublicIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado'), ('bloqueado', 'Bloqueado'), ('problema', 'Com problema'), ('reservado', 'Reservado'), ('inconsistente', 'Inconsistente')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('origem_importacao', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='core.ipblock')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_ips', to='core.client')),
                ('pppoe_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_ips', to='core.pppoeaccount')),
            ],
            options={
                'verbose_name': 'IP Público',
                'verbose_name_plural': 'IPs Públicos',
                'ordering': ['ip_address'],
            },
        ),
    ]
